/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.lrc.liferay.toolbuilder.model.StepDBE;
import org.lrc.liferay.toolbuilder.model.StepDBEModel;
import org.lrc.liferay.toolbuilder.model.StepDBESoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StepDBE service. Represents a row in the &quot;lrc_tb_StepDBE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.lrc.liferay.toolbuilder.model.StepDBEModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StepDBEImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see StepDBEImpl
 * @see org.lrc.liferay.toolbuilder.model.StepDBE
 * @see org.lrc.liferay.toolbuilder.model.StepDBEModel
 * @generated
 */
@JSON(strict = true)
public class StepDBEModelImpl extends BaseModelImpl<StepDBE>
	implements StepDBEModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a step d b e model instance should use the {@link org.lrc.liferay.toolbuilder.model.StepDBE} interface instead.
	 */
	public static final String TABLE_NAME = "lrc_tb_StepDBE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "stepDBEId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "stepType", Types.VARCHAR },
			{ "stepTypeId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table lrc_tb_StepDBE (stepDBEId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,stepType VARCHAR(75) null,stepTypeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table lrc_tb_StepDBE";
	public static final String ORDER_BY_JPQL = " ORDER BY stepDBE.stepDBEId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY lrc_tb_StepDBE.stepDBEId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.lrc.liferay.toolbuilder.model.StepDBE"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.lrc.liferay.toolbuilder.model.StepDBE"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.lrc.liferay.toolbuilder.model.StepDBE"),
			true);
	public static long STEPDBEID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StepDBE toModel(StepDBESoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StepDBE model = new StepDBEImpl();

		model.setStepDBEId(soapModel.getStepDBEId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStepType(soapModel.getStepType());
		model.setStepTypeId(soapModel.getStepTypeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StepDBE> toModels(StepDBESoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StepDBE> models = new ArrayList<StepDBE>(soapModels.length);

		for (StepDBESoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_LRC_TB_CS_STEP_NAME = "lrc_tb_CS_Step";
	public static final Object[][] MAPPING_TABLE_LRC_TB_CS_STEP_COLUMNS = {
			{ "compositeStepDBEId", Types.BIGINT },
			{ "stepDBEId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_LRC_TB_CS_STEP_SQL_CREATE = "create table lrc_tb_CS_Step (compositeStepDBEId LONG not null,stepDBEId LONG not null,primary key (compositeStepDBEId, stepDBEId))";
	public static final boolean FINDER_CACHE_ENABLED_LRC_TB_CS_STEP = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.lrc_tb_CS_Step"), true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.lrc.liferay.toolbuilder.model.StepDBE"));

	public StepDBEModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _stepDBEId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStepDBEId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stepDBEId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StepDBE.class;
	}

	@Override
	public String getModelClassName() {
		return StepDBE.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("stepDBEId", getStepDBEId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("stepType", getStepType());
		attributes.put("stepTypeId", getStepTypeId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long stepDBEId = (Long)attributes.get("stepDBEId");

		if (stepDBEId != null) {
			setStepDBEId(stepDBEId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String stepType = (String)attributes.get("stepType");

		if (stepType != null) {
			setStepType(stepType);
		}

		Long stepTypeId = (Long)attributes.get("stepTypeId");

		if (stepTypeId != null) {
			setStepTypeId(stepTypeId);
		}
	}

	@JSON
	@Override
	public long getStepDBEId() {
		return _stepDBEId;
	}

	@Override
	public void setStepDBEId(long stepDBEId) {
		_columnBitmask |= STEPDBEID_COLUMN_BITMASK;

		if (!_setOriginalStepDBEId) {
			_setOriginalStepDBEId = true;

			_originalStepDBEId = _stepDBEId;
		}

		_stepDBEId = stepDBEId;
	}

	public long getOriginalStepDBEId() {
		return _originalStepDBEId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getStepType() {
		if (_stepType == null) {
			return StringPool.BLANK;
		}
		else {
			return _stepType;
		}
	}

	@Override
	public void setStepType(String stepType) {
		_stepType = stepType;
	}

	@JSON
	@Override
	public long getStepTypeId() {
		return _stepTypeId;
	}

	@Override
	public void setStepTypeId(long stepTypeId) {
		_stepTypeId = stepTypeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			StepDBE.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StepDBE toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StepDBE)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StepDBEImpl stepDBEImpl = new StepDBEImpl();

		stepDBEImpl.setStepDBEId(getStepDBEId());
		stepDBEImpl.setGroupId(getGroupId());
		stepDBEImpl.setCompanyId(getCompanyId());
		stepDBEImpl.setUserId(getUserId());
		stepDBEImpl.setUserName(getUserName());
		stepDBEImpl.setCreateDate(getCreateDate());
		stepDBEImpl.setModifiedDate(getModifiedDate());
		stepDBEImpl.setStepType(getStepType());
		stepDBEImpl.setStepTypeId(getStepTypeId());

		stepDBEImpl.resetOriginalValues();

		return stepDBEImpl;
	}

	@Override
	public int compareTo(StepDBE stepDBE) {
		long primaryKey = stepDBE.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StepDBE)) {
			return false;
		}

		StepDBE stepDBE = (StepDBE)obj;

		long primaryKey = stepDBE.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		StepDBEModelImpl stepDBEModelImpl = this;

		stepDBEModelImpl._originalStepDBEId = stepDBEModelImpl._stepDBEId;

		stepDBEModelImpl._setOriginalStepDBEId = false;

		stepDBEModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StepDBE> toCacheModel() {
		StepDBECacheModel stepDBECacheModel = new StepDBECacheModel();

		stepDBECacheModel.stepDBEId = getStepDBEId();

		stepDBECacheModel.groupId = getGroupId();

		stepDBECacheModel.companyId = getCompanyId();

		stepDBECacheModel.userId = getUserId();

		stepDBECacheModel.userName = getUserName();

		String userName = stepDBECacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			stepDBECacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			stepDBECacheModel.createDate = createDate.getTime();
		}
		else {
			stepDBECacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			stepDBECacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			stepDBECacheModel.modifiedDate = Long.MIN_VALUE;
		}

		stepDBECacheModel.stepType = getStepType();

		String stepType = stepDBECacheModel.stepType;

		if ((stepType != null) && (stepType.length() == 0)) {
			stepDBECacheModel.stepType = null;
		}

		stepDBECacheModel.stepTypeId = getStepTypeId();

		return stepDBECacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{stepDBEId=");
		sb.append(getStepDBEId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", stepType=");
		sb.append(getStepType());
		sb.append(", stepTypeId=");
		sb.append(getStepTypeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("org.lrc.liferay.toolbuilder.model.StepDBE");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>stepDBEId</column-name><column-value><![CDATA[");
		sb.append(getStepDBEId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stepType</column-name><column-value><![CDATA[");
		sb.append(getStepType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stepTypeId</column-name><column-value><![CDATA[");
		sb.append(getStepTypeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = StepDBE.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			StepDBE.class
		};
	private long _stepDBEId;
	private long _originalStepDBEId;
	private boolean _setOriginalStepDBEId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _stepType;
	private long _stepTypeId;
	private long _columnBitmask;
	private StepDBE _escapedModel;
}