/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.lrc.liferay.toolbuilder.service.persistence.StepDefsCompositeStepDefDBEPK;

import java.io.Serializable;

/**
 * The base model interface for the StepDefsCompositeStepDefDBE service. Represents a row in the &quot;lrc_tb_StepDefsCompositeStepDefDBE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lrc.liferay.toolbuilder.model.impl.StepDefsCompositeStepDefDBEModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lrc.liferay.toolbuilder.model.impl.StepDefsCompositeStepDefDBEImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see StepDefsCompositeStepDefDBE
 * @see org.lrc.liferay.toolbuilder.model.impl.StepDefsCompositeStepDefDBEImpl
 * @see org.lrc.liferay.toolbuilder.model.impl.StepDefsCompositeStepDefDBEModelImpl
 * @generated
 */
public interface StepDefsCompositeStepDefDBEModel extends BaseModel<StepDefsCompositeStepDefDBE> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a step defs composite step def d b e model instance should use the {@link StepDefsCompositeStepDefDBE} interface instead.
	 */

	/**
	 * Returns the primary key of this step defs composite step def d b e.
	 *
	 * @return the primary key of this step defs composite step def d b e
	 */
	public StepDefsCompositeStepDefDBEPK getPrimaryKey();

	/**
	 * Sets the primary key of this step defs composite step def d b e.
	 *
	 * @param primaryKey the primary key of this step defs composite step def d b e
	 */
	public void setPrimaryKey(StepDefsCompositeStepDefDBEPK primaryKey);

	/**
	 * Returns the composite step def d b e ID of this step defs composite step def d b e.
	 *
	 * @return the composite step def d b e ID of this step defs composite step def d b e
	 */
	public long getCompositeStepDefDBEId();

	/**
	 * Sets the composite step def d b e ID of this step defs composite step def d b e.
	 *
	 * @param compositeStepDefDBEId the composite step def d b e ID of this step defs composite step def d b e
	 */
	public void setCompositeStepDefDBEId(long compositeStepDefDBEId);

	/**
	 * Returns the step def d b e ID of this step defs composite step def d b e.
	 *
	 * @return the step def d b e ID of this step defs composite step def d b e
	 */
	public long getStepDefDBEId();

	/**
	 * Sets the step def d b e ID of this step defs composite step def d b e.
	 *
	 * @param stepDefDBEId the step def d b e ID of this step defs composite step def d b e
	 */
	public void setStepDefDBEId(long stepDefDBEId);

	/**
	 * Returns the step index of this step defs composite step def d b e.
	 *
	 * @return the step index of this step defs composite step def d b e
	 */
	public int getStepIndex();

	/**
	 * Sets the step index of this step defs composite step def d b e.
	 *
	 * @param stepIndex the step index of this step defs composite step def d b e
	 */
	public void setStepIndex(int stepIndex);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.lrc.liferay.toolbuilder.model.StepDefsCompositeStepDefDBE stepDefsCompositeStepDefDBE);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.lrc.liferay.toolbuilder.model.StepDefsCompositeStepDefDBE> toCacheModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.StepDefsCompositeStepDefDBE toEscapedModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.StepDefsCompositeStepDefDBE toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}